package com.amao.ad2.db;

import com.amao.ad2.model.AdGroup;
import com.amao.ad2.model.AdGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AdGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    int countByExample(AdGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    int deleteByExample(AdGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    int insert(AdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    int insertSelective(AdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    List<AdGroup> selectByExample(AdGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    AdGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") AdGroup record, @Param("example") AdGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    int updateByExample(@Param("record") AdGroup record, @Param("example") AdGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    int updateByPrimaryKeySelective(AdGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    int updateByPrimaryKey(AdGroup record);
}