package com.amao.ad2.model;

public class Target {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.target_url
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private String targetUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.link_url
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.display_type
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private String displayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.comment
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.user_id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target.material_id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private Integer materialId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.id
     *
     * @return the value of target.id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.id
     *
     * @param id the value for target.id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.target_url
     *
     * @return the value of target.target_url
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public String getTargetUrl() {
        return targetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.target_url
     *
     * @param targetUrl the value for target.target_url
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setTargetUrl(String targetUrl) {
        this.targetUrl = targetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.link_url
     *
     * @return the value of target.link_url
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.link_url
     *
     * @param linkUrl the value for target.link_url
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.display_type
     *
     * @return the value of target.display_type
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public String getDisplayType() {
        return displayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.display_type
     *
     * @param displayType the value for target.display_type
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setDisplayType(String displayType) {
        this.displayType = displayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.comment
     *
     * @return the value of target.comment
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.comment
     *
     * @param comment the value for target.comment
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.user_id
     *
     * @return the value of target.user_id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.user_id
     *
     * @param userId the value for target.user_id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target.material_id
     *
     * @return the value of target.material_id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public Integer getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target.material_id
     *
     * @param materialId the value for target.material_id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }
}