package com.amao.wechat.model;

import java.util.Date;

public class AdGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.id
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.user_id
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.province
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.city
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.landmark_building
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private String landmarkBuilding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.gender
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.age_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private String ageGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.ad_like
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private String adLike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.launch_time_start
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private Date launchTimeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.launch_time_end
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private Date launchTimeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.job_role
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private String jobRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.income
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private String income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.consumption_capacity
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private String consumptionCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.Launch_budget
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private Long launchBudget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.pv
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private Long pv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_group.uv
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    private Long uv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.id
     *
     * @return the value of ad_group.id
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.id
     *
     * @param id the value for ad_group.id
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.user_id
     *
     * @return the value of ad_group.user_id
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.user_id
     *
     * @param userId the value for ad_group.user_id
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.province
     *
     * @return the value of ad_group.province
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.province
     *
     * @param province the value for ad_group.province
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.city
     *
     * @return the value of ad_group.city
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.city
     *
     * @param city the value for ad_group.city
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.landmark_building
     *
     * @return the value of ad_group.landmark_building
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public String getLandmarkBuilding() {
        return landmarkBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.landmark_building
     *
     * @param landmarkBuilding the value for ad_group.landmark_building
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setLandmarkBuilding(String landmarkBuilding) {
        this.landmarkBuilding = landmarkBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.gender
     *
     * @return the value of ad_group.gender
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.gender
     *
     * @param gender the value for ad_group.gender
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.age_group
     *
     * @return the value of ad_group.age_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public String getAgeGroup() {
        return ageGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.age_group
     *
     * @param ageGroup the value for ad_group.age_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setAgeGroup(String ageGroup) {
        this.ageGroup = ageGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.ad_like
     *
     * @return the value of ad_group.ad_like
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public String getAdLike() {
        return adLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.ad_like
     *
     * @param adLike the value for ad_group.ad_like
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setAdLike(String adLike) {
        this.adLike = adLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.launch_time_start
     *
     * @return the value of ad_group.launch_time_start
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public Date getLaunchTimeStart() {
        return launchTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.launch_time_start
     *
     * @param launchTimeStart the value for ad_group.launch_time_start
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setLaunchTimeStart(Date launchTimeStart) {
        this.launchTimeStart = launchTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.launch_time_end
     *
     * @return the value of ad_group.launch_time_end
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public Date getLaunchTimeEnd() {
        return launchTimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.launch_time_end
     *
     * @param launchTimeEnd the value for ad_group.launch_time_end
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setLaunchTimeEnd(Date launchTimeEnd) {
        this.launchTimeEnd = launchTimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.job_role
     *
     * @return the value of ad_group.job_role
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public String getJobRole() {
        return jobRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.job_role
     *
     * @param jobRole the value for ad_group.job_role
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setJobRole(String jobRole) {
        this.jobRole = jobRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.income
     *
     * @return the value of ad_group.income
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public String getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.income
     *
     * @param income the value for ad_group.income
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setIncome(String income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.consumption_capacity
     *
     * @return the value of ad_group.consumption_capacity
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public String getConsumptionCapacity() {
        return consumptionCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.consumption_capacity
     *
     * @param consumptionCapacity the value for ad_group.consumption_capacity
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setConsumptionCapacity(String consumptionCapacity) {
        this.consumptionCapacity = consumptionCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.Launch_budget
     *
     * @return the value of ad_group.Launch_budget
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public Long getLaunchBudget() {
        return launchBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.Launch_budget
     *
     * @param launchBudget the value for ad_group.Launch_budget
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setLaunchBudget(Long launchBudget) {
        this.launchBudget = launchBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.pv
     *
     * @return the value of ad_group.pv
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public Long getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.pv
     *
     * @param pv the value for ad_group.pv
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setPv(Long pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_group.uv
     *
     * @return the value of ad_group.uv
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public Long getUv() {
        return uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_group.uv
     *
     * @param uv the value for ad_group.uv
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setUv(Long uv) {
        this.uv = uv;
    }
}