package com.amao.wechat.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AdGroupExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public AdGroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingIsNull() {
            addCriterion("landmark_building is null");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingIsNotNull() {
            addCriterion("landmark_building is not null");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingEqualTo(String value) {
            addCriterion("landmark_building =", value, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingNotEqualTo(String value) {
            addCriterion("landmark_building <>", value, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingGreaterThan(String value) {
            addCriterion("landmark_building >", value, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingGreaterThanOrEqualTo(String value) {
            addCriterion("landmark_building >=", value, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingLessThan(String value) {
            addCriterion("landmark_building <", value, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingLessThanOrEqualTo(String value) {
            addCriterion("landmark_building <=", value, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingLike(String value) {
            addCriterion("landmark_building like", value, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingNotLike(String value) {
            addCriterion("landmark_building not like", value, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingIn(List<String> values) {
            addCriterion("landmark_building in", values, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingNotIn(List<String> values) {
            addCriterion("landmark_building not in", values, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingBetween(String value1, String value2) {
            addCriterion("landmark_building between", value1, value2, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andLandmarkBuildingNotBetween(String value1, String value2) {
            addCriterion("landmark_building not between", value1, value2, "landmarkBuilding");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andAgeGroupIsNull() {
            addCriterion("age_group is null");
            return (Criteria) this;
        }

        public Criteria andAgeGroupIsNotNull() {
            addCriterion("age_group is not null");
            return (Criteria) this;
        }

        public Criteria andAgeGroupEqualTo(String value) {
            addCriterion("age_group =", value, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupNotEqualTo(String value) {
            addCriterion("age_group <>", value, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupGreaterThan(String value) {
            addCriterion("age_group >", value, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupGreaterThanOrEqualTo(String value) {
            addCriterion("age_group >=", value, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupLessThan(String value) {
            addCriterion("age_group <", value, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupLessThanOrEqualTo(String value) {
            addCriterion("age_group <=", value, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupLike(String value) {
            addCriterion("age_group like", value, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupNotLike(String value) {
            addCriterion("age_group not like", value, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupIn(List<String> values) {
            addCriterion("age_group in", values, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupNotIn(List<String> values) {
            addCriterion("age_group not in", values, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupBetween(String value1, String value2) {
            addCriterion("age_group between", value1, value2, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAgeGroupNotBetween(String value1, String value2) {
            addCriterion("age_group not between", value1, value2, "ageGroup");
            return (Criteria) this;
        }

        public Criteria andAdLikeIsNull() {
            addCriterion("ad_like is null");
            return (Criteria) this;
        }

        public Criteria andAdLikeIsNotNull() {
            addCriterion("ad_like is not null");
            return (Criteria) this;
        }

        public Criteria andAdLikeEqualTo(String value) {
            addCriterion("ad_like =", value, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeNotEqualTo(String value) {
            addCriterion("ad_like <>", value, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeGreaterThan(String value) {
            addCriterion("ad_like >", value, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeGreaterThanOrEqualTo(String value) {
            addCriterion("ad_like >=", value, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeLessThan(String value) {
            addCriterion("ad_like <", value, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeLessThanOrEqualTo(String value) {
            addCriterion("ad_like <=", value, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeLike(String value) {
            addCriterion("ad_like like", value, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeNotLike(String value) {
            addCriterion("ad_like not like", value, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeIn(List<String> values) {
            addCriterion("ad_like in", values, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeNotIn(List<String> values) {
            addCriterion("ad_like not in", values, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeBetween(String value1, String value2) {
            addCriterion("ad_like between", value1, value2, "adLike");
            return (Criteria) this;
        }

        public Criteria andAdLikeNotBetween(String value1, String value2) {
            addCriterion("ad_like not between", value1, value2, "adLike");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartIsNull() {
            addCriterion("launch_time_start is null");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartIsNotNull() {
            addCriterion("launch_time_start is not null");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartEqualTo(Date value) {
            addCriterionForJDBCTime("launch_time_start =", value, "launchTimeStart");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartNotEqualTo(Date value) {
            addCriterionForJDBCTime("launch_time_start <>", value, "launchTimeStart");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartGreaterThan(Date value) {
            addCriterionForJDBCTime("launch_time_start >", value, "launchTimeStart");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("launch_time_start >=", value, "launchTimeStart");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartLessThan(Date value) {
            addCriterionForJDBCTime("launch_time_start <", value, "launchTimeStart");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("launch_time_start <=", value, "launchTimeStart");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartIn(List<Date> values) {
            addCriterionForJDBCTime("launch_time_start in", values, "launchTimeStart");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartNotIn(List<Date> values) {
            addCriterionForJDBCTime("launch_time_start not in", values, "launchTimeStart");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("launch_time_start between", value1, value2, "launchTimeStart");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeStartNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("launch_time_start not between", value1, value2, "launchTimeStart");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndIsNull() {
            addCriterion("launch_time_end is null");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndIsNotNull() {
            addCriterion("launch_time_end is not null");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndEqualTo(Date value) {
            addCriterionForJDBCTime("launch_time_end =", value, "launchTimeEnd");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndNotEqualTo(Date value) {
            addCriterionForJDBCTime("launch_time_end <>", value, "launchTimeEnd");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndGreaterThan(Date value) {
            addCriterionForJDBCTime("launch_time_end >", value, "launchTimeEnd");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("launch_time_end >=", value, "launchTimeEnd");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndLessThan(Date value) {
            addCriterionForJDBCTime("launch_time_end <", value, "launchTimeEnd");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("launch_time_end <=", value, "launchTimeEnd");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndIn(List<Date> values) {
            addCriterionForJDBCTime("launch_time_end in", values, "launchTimeEnd");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndNotIn(List<Date> values) {
            addCriterionForJDBCTime("launch_time_end not in", values, "launchTimeEnd");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("launch_time_end between", value1, value2, "launchTimeEnd");
            return (Criteria) this;
        }

        public Criteria andLaunchTimeEndNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("launch_time_end not between", value1, value2, "launchTimeEnd");
            return (Criteria) this;
        }

        public Criteria andJobRoleIsNull() {
            addCriterion("job_role is null");
            return (Criteria) this;
        }

        public Criteria andJobRoleIsNotNull() {
            addCriterion("job_role is not null");
            return (Criteria) this;
        }

        public Criteria andJobRoleEqualTo(String value) {
            addCriterion("job_role =", value, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleNotEqualTo(String value) {
            addCriterion("job_role <>", value, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleGreaterThan(String value) {
            addCriterion("job_role >", value, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleGreaterThanOrEqualTo(String value) {
            addCriterion("job_role >=", value, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleLessThan(String value) {
            addCriterion("job_role <", value, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleLessThanOrEqualTo(String value) {
            addCriterion("job_role <=", value, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleLike(String value) {
            addCriterion("job_role like", value, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleNotLike(String value) {
            addCriterion("job_role not like", value, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleIn(List<String> values) {
            addCriterion("job_role in", values, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleNotIn(List<String> values) {
            addCriterion("job_role not in", values, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleBetween(String value1, String value2) {
            addCriterion("job_role between", value1, value2, "jobRole");
            return (Criteria) this;
        }

        public Criteria andJobRoleNotBetween(String value1, String value2) {
            addCriterion("job_role not between", value1, value2, "jobRole");
            return (Criteria) this;
        }

        public Criteria andIncomeIsNull() {
            addCriterion("income is null");
            return (Criteria) this;
        }

        public Criteria andIncomeIsNotNull() {
            addCriterion("income is not null");
            return (Criteria) this;
        }

        public Criteria andIncomeEqualTo(String value) {
            addCriterion("income =", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeNotEqualTo(String value) {
            addCriterion("income <>", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeGreaterThan(String value) {
            addCriterion("income >", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeGreaterThanOrEqualTo(String value) {
            addCriterion("income >=", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeLessThan(String value) {
            addCriterion("income <", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeLessThanOrEqualTo(String value) {
            addCriterion("income <=", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeLike(String value) {
            addCriterion("income like", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeNotLike(String value) {
            addCriterion("income not like", value, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeIn(List<String> values) {
            addCriterion("income in", values, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeNotIn(List<String> values) {
            addCriterion("income not in", values, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeBetween(String value1, String value2) {
            addCriterion("income between", value1, value2, "income");
            return (Criteria) this;
        }

        public Criteria andIncomeNotBetween(String value1, String value2) {
            addCriterion("income not between", value1, value2, "income");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityIsNull() {
            addCriterion("consumption_capacity is null");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityIsNotNull() {
            addCriterion("consumption_capacity is not null");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityEqualTo(String value) {
            addCriterion("consumption_capacity =", value, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityNotEqualTo(String value) {
            addCriterion("consumption_capacity <>", value, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityGreaterThan(String value) {
            addCriterion("consumption_capacity >", value, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityGreaterThanOrEqualTo(String value) {
            addCriterion("consumption_capacity >=", value, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityLessThan(String value) {
            addCriterion("consumption_capacity <", value, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityLessThanOrEqualTo(String value) {
            addCriterion("consumption_capacity <=", value, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityLike(String value) {
            addCriterion("consumption_capacity like", value, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityNotLike(String value) {
            addCriterion("consumption_capacity not like", value, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityIn(List<String> values) {
            addCriterion("consumption_capacity in", values, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityNotIn(List<String> values) {
            addCriterion("consumption_capacity not in", values, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityBetween(String value1, String value2) {
            addCriterion("consumption_capacity between", value1, value2, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andConsumptionCapacityNotBetween(String value1, String value2) {
            addCriterion("consumption_capacity not between", value1, value2, "consumptionCapacity");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetIsNull() {
            addCriterion("Launch_budget is null");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetIsNotNull() {
            addCriterion("Launch_budget is not null");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetEqualTo(Long value) {
            addCriterion("Launch_budget =", value, "launchBudget");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetNotEqualTo(Long value) {
            addCriterion("Launch_budget <>", value, "launchBudget");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetGreaterThan(Long value) {
            addCriterion("Launch_budget >", value, "launchBudget");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetGreaterThanOrEqualTo(Long value) {
            addCriterion("Launch_budget >=", value, "launchBudget");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetLessThan(Long value) {
            addCriterion("Launch_budget <", value, "launchBudget");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetLessThanOrEqualTo(Long value) {
            addCriterion("Launch_budget <=", value, "launchBudget");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetIn(List<Long> values) {
            addCriterion("Launch_budget in", values, "launchBudget");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetNotIn(List<Long> values) {
            addCriterion("Launch_budget not in", values, "launchBudget");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetBetween(Long value1, Long value2) {
            addCriterion("Launch_budget between", value1, value2, "launchBudget");
            return (Criteria) this;
        }

        public Criteria andLaunchBudgetNotBetween(Long value1, Long value2) {
            addCriterion("Launch_budget not between", value1, value2, "launchBudget");
            return (Criteria) this;
        }

        public Criteria andPvIsNull() {
            addCriterion("pv is null");
            return (Criteria) this;
        }

        public Criteria andPvIsNotNull() {
            addCriterion("pv is not null");
            return (Criteria) this;
        }

        public Criteria andPvEqualTo(Long value) {
            addCriterion("pv =", value, "pv");
            return (Criteria) this;
        }

        public Criteria andPvNotEqualTo(Long value) {
            addCriterion("pv <>", value, "pv");
            return (Criteria) this;
        }

        public Criteria andPvGreaterThan(Long value) {
            addCriterion("pv >", value, "pv");
            return (Criteria) this;
        }

        public Criteria andPvGreaterThanOrEqualTo(Long value) {
            addCriterion("pv >=", value, "pv");
            return (Criteria) this;
        }

        public Criteria andPvLessThan(Long value) {
            addCriterion("pv <", value, "pv");
            return (Criteria) this;
        }

        public Criteria andPvLessThanOrEqualTo(Long value) {
            addCriterion("pv <=", value, "pv");
            return (Criteria) this;
        }

        public Criteria andPvIn(List<Long> values) {
            addCriterion("pv in", values, "pv");
            return (Criteria) this;
        }

        public Criteria andPvNotIn(List<Long> values) {
            addCriterion("pv not in", values, "pv");
            return (Criteria) this;
        }

        public Criteria andPvBetween(Long value1, Long value2) {
            addCriterion("pv between", value1, value2, "pv");
            return (Criteria) this;
        }

        public Criteria andPvNotBetween(Long value1, Long value2) {
            addCriterion("pv not between", value1, value2, "pv");
            return (Criteria) this;
        }

        public Criteria andUvIsNull() {
            addCriterion("uv is null");
            return (Criteria) this;
        }

        public Criteria andUvIsNotNull() {
            addCriterion("uv is not null");
            return (Criteria) this;
        }

        public Criteria andUvEqualTo(Long value) {
            addCriterion("uv =", value, "uv");
            return (Criteria) this;
        }

        public Criteria andUvNotEqualTo(Long value) {
            addCriterion("uv <>", value, "uv");
            return (Criteria) this;
        }

        public Criteria andUvGreaterThan(Long value) {
            addCriterion("uv >", value, "uv");
            return (Criteria) this;
        }

        public Criteria andUvGreaterThanOrEqualTo(Long value) {
            addCriterion("uv >=", value, "uv");
            return (Criteria) this;
        }

        public Criteria andUvLessThan(Long value) {
            addCriterion("uv <", value, "uv");
            return (Criteria) this;
        }

        public Criteria andUvLessThanOrEqualTo(Long value) {
            addCriterion("uv <=", value, "uv");
            return (Criteria) this;
        }

        public Criteria andUvIn(List<Long> values) {
            addCriterion("uv in", values, "uv");
            return (Criteria) this;
        }

        public Criteria andUvNotIn(List<Long> values) {
            addCriterion("uv not in", values, "uv");
            return (Criteria) this;
        }

        public Criteria andUvBetween(Long value1, Long value2) {
            addCriterion("uv between", value1, value2, "uv");
            return (Criteria) this;
        }

        public Criteria andUvNotBetween(Long value1, Long value2) {
            addCriterion("uv not between", value1, value2, "uv");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_group
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 12 14:46:59 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ad_group
     *
     * @mbggenerated Tue Jan 12 14:46:59 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}