package com.amao.wechat.model;

public class Material {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.name
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.content_type
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.comment
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.user_id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material.content
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.id
     *
     * @return the value of material.id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.id
     *
     * @param id the value for material.id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.name
     *
     * @return the value of material.name
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.name
     *
     * @param name the value for material.name
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.content_type
     *
     * @return the value of material.content_type
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.content_type
     *
     * @param contentType the value for material.content_type
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.comment
     *
     * @return the value of material.comment
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.comment
     *
     * @param comment the value for material.comment
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.user_id
     *
     * @return the value of material.user_id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.user_id
     *
     * @param userId the value for material.user_id
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material.content
     *
     * @return the value of material.content
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material.content
     *
     * @param content the value for material.content
     *
     * @mbggenerated Mon Dec 14 11:17:03 CST 2015
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}